sudo: required
services:
  - docker
install: true
jobs:
  include:
    - stage: continuous_integration
      if: NOT tag IS present
      script:
        - make
      env:
        - VERSION=$TRAVIS_COMMIT
#    - stage: deployment
#      if: tag IS present
#      script: make install && make publish
