sudo: required
services:
  - docker
install: false
jobs:
  include:
    - stage: continuous_integration
      if: NOT tag IS present
      script: make install
    - stage: deployment
      if: tag IS present
      script: make install && make publish
