sudo: required
services:
  - docker
install: true
jobs:
  include:
    - stage: continuous_integration
      if: NOT tag IS present
      script:
        - docker build -t nestjs/cli:$TRAVIS_COMMIT .
        - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        - docker push nestjs/cli:$TRAVIS_COMMIT
#    - stage: deployment
#      if: tag IS present
#      script: make install && make publish
